name: "Terraform"
on:
  workflow_call:
    inputs:
      abc:
        required: true
        type: string

jobs:
  build:
    environment: ${{ inputs.abc }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
